// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for author documents */
interface AuthorDocumentData {
    /**
     * name field in *author*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: author.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * about field in *author*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.about
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about: prismicT.RichTextField;
    /**
     * image field in *author*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: author.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * small_description field in *author*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.small_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    small_description: prismicT.RichTextField;
}
/**
 * author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;
/** Content for Contatos documents */
type ContatosDocumentData = Record<string, never>;
/**
 * Contatos document from Prismic
 *
 * - **API ID**: `contatos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContatosDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ContatosDocumentData>, "contatos", Lang>;
/** Content for displayed_arts_images documents */
interface DisplayedArtsImagesDocumentData {
    /**
     * img field in *displayed_arts_images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: displayed_arts_images.img
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img: prismicT.ImageField<never>;
    /**
     * name field in *displayed_arts_images*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: displayed_arts_images.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Slice Zone field in *displayed_arts_images*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: displayed_arts_images.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<DisplayedArtsImagesDocumentDataSlicesSlice>;
}
/**
 * Slice for *displayed_arts_images → Slice Zone*
 *
 */
type DisplayedArtsImagesDocumentDataSlicesSlice = GalleryPortfolioSlice;
/**
 * displayed_arts_images document from Prismic
 *
 * - **API ID**: `displayed_arts_images`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DisplayedArtsImagesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DisplayedArtsImagesDocumentData>, "displayed_arts_images", Lang>;
/** Content for portfolio_page_texts documents */
interface PortfolioPageTextsDocumentData {
    /**
     * title field in *portfolio_page_texts*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_page_texts.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * description field in *portfolio_page_texts*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_page_texts.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Slice Zone field in *portfolio_page_texts*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_page_texts.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PortfolioPageTextsDocumentDataSlicesSlice>;
}
/**
 * Slice for *portfolio_page_texts → Slice Zone*
 *
 */
type PortfolioPageTextsDocumentDataSlicesSlice = GalleryPortfolioSlice;
/**
 * portfolio_page_texts document from Prismic
 *
 * - **API ID**: `portfolio_page_texts`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioPageTextsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PortfolioPageTextsDocumentData>, "portfolio_page_texts", Lang>;
export type AllDocumentTypes = AuthorDocument | ContatosDocument | DisplayedArtsImagesDocument | PortfolioPageTextsDocument;
/**
 * Item in GalleryPortfolio → Items
 *
 */
export interface GalleryPortfolioSliceDefaultItem {
    /**
     * image field in *GalleryPortfolio → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery_portfolio.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * name field in *GalleryPortfolio → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery_portfolio.items[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
}
/**
 * Default variation for GalleryPortfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: `GalleryPortfolio`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GalleryPortfolioSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<GalleryPortfolioSliceDefaultItem>>;
/**
 * Slice variation for *GalleryPortfolio*
 *
 */
type GalleryPortfolioSliceVariation = GalleryPortfolioSliceDefault;
/**
 * GalleryPortfolio Shared Slice
 *
 * - **API ID**: `gallery_portfolio`
 * - **Description**: `GalleryPortfolio`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GalleryPortfolioSlice = prismicT.SharedSlice<"gallery_portfolio", GalleryPortfolioSliceVariation>;
/**
 * Primary content in PortfolioTitle → Primary
 *
 */
interface PortfolioTitleSliceDefaultPrimary {
    /**
     * Title field in *PortfolioTitle → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: portfolio_title.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *PortfolioTitle → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: portfolio_title.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for PortfolioTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PortfolioTitle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PortfolioTitleSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PortfolioTitleSliceDefaultPrimary>, never>;
/**
 * Slice variation for *PortfolioTitle*
 *
 */
type PortfolioTitleSliceVariation = PortfolioTitleSliceDefault;
/**
 * PortfolioTitle Shared Slice
 *
 * - **API ID**: `portfolio_title`
 * - **Description**: `PortfolioTitle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PortfolioTitleSlice = prismicT.SharedSlice<"portfolio_title", PortfolioTitleSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AuthorDocumentData, AuthorDocument, ContatosDocumentData, ContatosDocument, DisplayedArtsImagesDocumentData, DisplayedArtsImagesDocumentDataSlicesSlice, DisplayedArtsImagesDocument, PortfolioPageTextsDocumentData, PortfolioPageTextsDocumentDataSlicesSlice, PortfolioPageTextsDocument, AllDocumentTypes, GalleryPortfolioSliceDefaultItem, GalleryPortfolioSliceDefault, GalleryPortfolioSliceVariation, GalleryPortfolioSlice, PortfolioTitleSliceDefaultPrimary, PortfolioTitleSliceDefault, PortfolioTitleSliceVariation, PortfolioTitleSlice };
    }
}
