// Code generated by Slice Machine. DO NOT EDIT.

import GalleryPortfolio from './GalleryPortfolio';
import PortfolioTitle from './PortfolioTitle';

export {
	GalleryPortfolio,
	PortfolioTitle,
};

export const components = {
	gallery_portfolio: GalleryPortfolio,
	portfolio_title: PortfolioTitle,
};
