// Code generated by Slice Machine. DO NOT EDIT.

import GalleryPortfolio from './GalleryPortfolio';
import Heading from './Heading';
import NavItemLink from './NavItemLink';
import PortfolioTitle from './PortfolioTitle';

export {
	GalleryPortfolio,
	Heading,
	NavItemLink,
	PortfolioTitle,
};

export const components = {
	gallery_portfolio: GalleryPortfolio,
	heading: Heading,
	nav_item_link: NavItemLink,
	portfolio_title: PortfolioTitle,
};
